# Generated by Django 5.2.4 on 2025-07-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0002_commande_lignedecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_commande',
            field=models.CharField(choices=[('salle', 'Service en salle'), ('livraison', 'Livraison')], default='salle', max_length=20),
        ),
    ]
