# Generated by Django 5.2.4 on 2025-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0002_table_reservation_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['numero'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveField(
            model_name='table',
            name='etat',
        ),
        migrations.AddField(
            model_name='table',
            name='est_disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
