# Generated by Django 5.2.4 on 2025-07-26 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0003_commande_adresse_livraison_commande_mode_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Réservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_réservation', models.DateField()),
                ('heure_réservation', models.TimeField()),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('est_confirmée', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='réservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date_réservation', 'heure_réservation'],
            },
        ),
    ]
