# Generated by Django 5.2.4 on 2025-07-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0005_reservation_commande_reservation_delete_réservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Client', 'Client'), ('Serveur', 'Serveur'), ('Cuisinier', 'Cuisinier'), ('Caissier', 'Caissier')], default='Client', max_length=20),
        ),
    ]
