# Generated by Django 5.2.4 on 2025-07-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0006_utilisateur_telephone_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
