# Generated by Django 5.2.4 on 2025-07-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0007_commande_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='moyen_paiement',
            field=models.CharField(choices=[('espece', 'Espèce'), ('paydunya', 'PayDunya')], default='espece', max_length=20),
        ),
    ]
