# Generated by Django 5.2.4 on 2025-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0008_commande_moyen_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
