# Generated by Django 5.2.4 on 2025-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_site', '0009_commande_telephone_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Client', 'Client'), ('Serveur', 'Serveur'), ('Cuisinier', 'Cuisinier'), ('Caissier', 'Caissier'), ('Livreur', 'Livreur')], default='Client', max_length=20),
        ),
    ]
